# Importing DATA

In [1]:
!pip install pdpbox

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 34.0 MB 1.3 MB/s 
     |████████████████████████████████| 13.1 MB 63.3 MB/s 
  Created wheel for pdpbox: filename=PDPbox-0.2.1-py3-none-any.whl size=35758224 sha256=0a5c1645ca9709367fdb217b30978c3350704726acc68a6d4ea22b5073c2def4
  Stored in directory: /root/.cache/pip/wheels/f4/d0/1a/b80035625c53131f52906a6fc4dd690d8efd2bf8af6a4015eb
Successfully built pdpbox
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.2.2
    Uninstalling matplotlib-3.2.2:
      Successfully uninstalled matplotlib-3.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [2]:
# Library
!pip install category_encoders
!pip install eli5
!pip install pandas-profiling==3.1.0
!pip install pdpbox

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 69 kB 3.3 MB/s 
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 216 kB 4.7 MB/s 
     |████████████████████████████████| 133 kB 59.4 MB/s 
  Created wheel for eli5: filename=eli5-0.13.0-py2.py3-none-any.whl size=107748 sha256=bcd2b64c7121b2617b378e6840b15270338ce91db4ddcb7a0f2972a7c8e73bd7
  Stored in directory: /root/.cache/pip/wheels/cc/3c/96/3ead31a8e6c20fc0f1a707fde2e05d49a80b1b4b30096573be
Successfully built eli5
  Attempting uninstall: jinja2
    Found existing installation: Jinja2 2.11.3
    Uninstalling Jinja2-2.11.3:
      Successfully uninstalled Jinja2-2.11.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask 1.1.4 requir

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Using cached matplotlib-3.1.1-cp37-cp37m-manylinux1_x86_64.whl (13.1 MB)
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.2
    Uninstalling matplotlib-3.5.2:
      Successfully uninstalled matplotlib-3.5.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-profiling 3.1.0 requires matplotlib>=3.2.0, but you have matplotlib 3.1.1 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.


In [3]:
### 이곳에서 과제를 진행해 주세요 ###
import numpy as np
import pandas as pd
# 파일 불러오기 (local에서 업로드)
#from google.colab import files
#files.upload()


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
df_yl = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NSDUH_2020_Tab.txt', sep="\t", encoding="ISO-8859-1", header=0)
df_yl.head()

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: DtypeWarning: Columns (2726) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


QUESTID2    FILEDATE  CIGEVER  CIGOFRSM  CIGWILYR  CIGTRY  CIGYFU  CIGMFU  \
0  10000182  10/25/2021        1        99        99      16    9999      99   
1  10001831  10/25/2021        1        99        99       8    9999      99   
2  10002722  10/25/2021        2        99        99     991    9991      91   
3  10002897  10/25/2021        2        99        99     991    9991      91   
4  10004677  10/25/2021        2         4         4     991    9991      91   

   CIGREC  CIG30USE  ...  GOVTPROG  INCOME  POVERTY3  PDEN10  COUTYP4  \
0       1        30  ...         2       4       3.0       3        3   
1       1        24  ...         2       3       3.0       2        2   
2      91        91  ...         2       2       3.0       1        1   
3      91        91  ...         2       4       3.0       1        1   
4      91        91  ...         2       4       3.0       2        2   

   MAIIN102  AIIND102  ANALWTQ1Q4_C  VESTRQ1Q4_C  VEREP  
0         2         2  16186.579071        40048      2  
1         2         2  16809.072854        40022      2  
2         2         2   1379.866862        40011      1  
3         2         2    422.776340        40007      1  
4         2         2    609.829709        40031      1  

[5 rows x 2890 columns]

In [6]:
df_yl.head()


QUESTID2    FILEDATE  CIGEVER  CIGOFRSM  CIGWILYR  CIGTRY  CIGYFU  CIGMFU  \
0  10000182  10/25/2021        1        99        99      16    9999      99   
1  10001831  10/25/2021        1        99        99       8    9999      99   
2  10002722  10/25/2021        2        99        99     991    9991      91   
3  10002897  10/25/2021        2        99        99     991    9991      91   
4  10004677  10/25/2021        2         4         4     991    9991      91   

   CIGREC  CIG30USE  ...  GOVTPROG  INCOME  POVERTY3  PDEN10  COUTYP4  \
0       1        30  ...         2       4       3.0       3        3   
1       1        24  ...         2       3       3.0       2        2   
2      91        91  ...         2       2       3.0       1        1   
3      91        91  ...         2       4       3.0       1        1   
4      91        91  ...         2       4       3.0       2        2   

   MAIIN102  AIIND102  ANALWTQ1Q4_C  VESTRQ1Q4_C  VEREP  
0         2         2  16186.579071        40048      2  
1         2         2  16809.072854        40022      2  
2         2         2   1379.866862        40011      1  
3         2         2    422.776340        40007      1  
4         2         2    609.829709        40031      1  

[5 rows x 2890 columns]

In [7]:
df_yl.info

<bound method DataFrame.info of        QUESTID2    FILEDATE  CIGEVER  CIGOFRSM  CIGWILYR  CIGTRY  CIGYFU  \
0      10000182  10/25/2021        1        99        99      16    9999   
1      10001831  10/25/2021        1        99        99       8    9999   
2      10002722  10/25/2021        2        99        99     991    9991   
3      10002897  10/25/2021        2        99        99     991    9991   
4      10004677  10/25/2021        2         4         4     991    9991   
...         ...         ...      ...       ...       ...     ...     ...   
32888  43070618  10/25/2021        2        99        99     991    9991   
32889  43071867  10/25/2021        2        99        99     991    9991   
32890  43074600  10/25/2021        2         4         4     991    9991   
32891  43074630  10/25/2021        2        99        99     991    9991   
32892  43075406  10/25/2021        1        99        99      15    9999   

       CIGMFU  CIGREC  CIG30USE  ...  GOVTPROG  INCOME 

In [8]:
df_yl.shape

(32893, 2890)

## 사용할 데이터 정리 (column, target)

In [9]:
col= ['CIG30USE',  # Number of days smoked cigarettes in past month
      'IRALCFY',  # Number of days used alcohol in past year
      'HEALTH',     # Health condition
      'WRKDHRSWK2',  # Number of hours worked in past week
      'IRHHSIZ2', # Number of people in household
      'IRKI17_2',  # Number of kids <18 y/o
      ]    
  # [drug_use] : IMPUTED DSM-5 SUBSTANCE USE DISORDER


In [10]:
drug_use = ['IRPYUD5ALC', # ALCOHOL USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5MRJ', # MARIJUANA USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5COC', # COCAINE USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5HER', # HEROIN USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5HAL', # HALLUCINOGEN USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5INH', # INHALANT USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5MTH', # METHAMPHETAMINE USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5PNR', # PAIN RELIEVER USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5TRQ', # TRANQUILIZER USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5STM', # STIMULANT USE DISORDER IN THE PAST YEAR - IMP REV
            'IRPYUD5SED'] # SEDATIVE USE DISORDER IN THE PAST YEAR - IMP REV 

In [11]:
alcohol_use = ['ALCEVER',  # EVER HAD DRINK OF ALCOHOLIC BEVERAGE
               'ALCTRY',   # AGE WHEN FIRST DRANK ALCOHOLIC BEVERAGE 1-66
               'ALCREC',   # TIME SINCE LAST DRANK ALCOHOLIC BEVERAGE
               'ALCYRTOT', # TOTAL # OF DAYS USED ALCOHOL IN PAST 12 MOS
               'ALBSTWAY', # EASIEST WAY TO TELL US # DAYS DRANK ALCOHOL
               'ALCDAYS',  # DAYS HAD ONE OR MORE DRINKS PAST 30 DAYS  1-30
               'ALCUS30D', # USUAL # OF DRINKS PER DAY PAST 30 DAYS
               ]

In [12]:
mental_health = ['DSTNRV30', # HOW OFTEN FELT NERVOUS PAST 30 DAY / 1-5 , 85, 94-99
                 'DSTHOP30', # During the past 30 days, how often did you feel hopeless? 
                 'DSTRST30', # During the past 30 days, how often did you feel restless or fidgety?
                 'DSTCHR30', # During the past 30 days, how often did you feel so sad or depressed that nothing could cheer you up? 
                 'DSTEFF30', # During the past 30 days, how often did you feel that everything was an effort?
                 'DSTNGD30', # During the past 30 days, how often did you feel down on yourself, no good, or worthless?
                 'K6SCMAX',   #a score with values ranging from 0 to 24 indicating the level of psychological distress during the worst month of the past year, that was not the past 30 days. 
                 'WHODASC2'  #f the daily activities that a respondent indicated having "moderate" or "severe" difficulty performing, or if the respondent indicated not performing the activity due to problems with emotions, nerves, or mental health.
                 ]  

In [13]:
religious =['SNRLGSVC', # During the past 12 months, how many times did you attend religious services?
             'SNRLGIMP', # Your religious beliefs are a very important part of your life.
             'SNRLDCSN', # Your religious beliefs influence how you make decisions in your life.
             'SNRLFRND'] # It is important that your friends share your religious beliefs

In [14]:
#df_AD = df_yl[df_yl.columns[pd.Series(df_yl.columns).str.startswith('AD')]]
Depression =['AMDELT', # Life time major depressive episode
             'AHLTMDE', # whether an adult reported seeing or talking to a health professional about MDE in the past year
             'AALTMDE', # whether an adult reported seeing or talking to an alternative service professional about MDE in the past year.
             'DSTWORST', # Was there a month in the past 12 months when you felt more depressed, anxious, or emotionally stressed than you felt during the past 30 days?
             'ADDPREV',  # SEVERAL DAYS OR LNGR WHEN FELT SAD/EMPTY/DPRSD
             'SMIPP_U'   # The predicted mental illness variables (e.g., SMIYR_U, AMIYR_U) 
                             # that were derived from the 2012 model were examined to determine how they were associated with the mental health predictor variables in the 2012 model.
                             # It was found that the 2012 model significantly overestimated the proportion of adults aged 18 or older with SMI (and those with AMI) who had suicidal thoughts in the past year
                             # and also the proportion of adults who had MDE in the past year. 
             ]

In [15]:
demographics = ['CATAG6', # Age category 6 levels
                'IRSEX',  # sex
                'IREDUHIGHST2', # eudcation 
                'IRPINC3', # resp tot Income
                'IRFAMIN3', # tot fam income
                # 'INCOME', # Total family income record
                #'POVERTY3', # RC-Poverty Level
                'PDEN10',  # Population density _ Geographic
                'COUTYP4', # County metro/nonmetro status
                ] 

In [16]:
df_yl.K6SCYR.value_counts()

12.0    672
6.0     598
18.0    523
7.0     515
10.0    506
5.0     495
4.0     494
11.0    471
9.0     469
24.0    468
8.0     457
13.0    456
14.0    447
3.0     434
16.0    396
15.0    383
2.0     343
17.0    342
19.0    273
20.0    225
21.0    201
1.0     175
22.0    172
23.0    123
0.0      49
Name: K6SCYR, dtype: int64

In [17]:
#df_demog= df_yl[demographics]
#df_depre= df_yl[Depression]
#df_mental= df_yl[mental_health]
#df_relig= df_yl[religious]
#df_col= df_yl[col]
#df_demog= df_yl[alcohol_use]
df_drug_yl= df_yl[drug_use]
df_drug_yl['AnyDrug']= df_drug_yl.sum(axis = 1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [18]:
df_drug_yl.head()

IRPYUD5ALC  IRPYUD5MRJ  IRPYUD5COC  IRPYUD5HER  IRPYUD5HAL  IRPYUD5INH  \
0           0           0           0           0           0           0   
1           1           0           0           0           0           0   
2           0           0           0           0           0           0   
3           0           0           0           0           0           0   
4           0           0           0           0           0           0   

   IRPYUD5MTH  IRPYUD5PNR  IRPYUD5TRQ  IRPYUD5STM  IRPYUD5SED  AnyDrug  
0           0           0           0           0           0        0  
1           0           0           0           0           0        1  
2           0           0           0           0           0        0  
3           0           0           0           0           0        0  
4           0           0           0           0           0        0

In [19]:
df_drug_yl['AnyDrug'].value_counts()

0    27550
1     4164
2      954
3      144
4       44
5       28
6        8
7        1
Name: AnyDrug, dtype: int64

In [20]:
df_drug_yl.replace({'AnyDrug':[2,3,4,5,6,7]},1, inplace = True)
df_drug_yl.replace({'AnyDrug':[2,3,4,5,6,7]},1, inplace = True)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value


In [21]:
columns_name = ['QUESTID2'] + demographics+ Depression+ mental_health+religious+col
df_20 = pd.DataFrame(df_yl,columns =columns_name)

In [22]:
df_20['target'] = df_drug_yl['AnyDrug']

In [23]:
df_20.head()

QUESTID2  CATAG6  IRSEX  IREDUHIGHST2  IRPINC3  IRFAMIN3  PDEN10  COUTYP4  \
0  10000182       4      1             9        7         7       3        3   
1  10001831       4      1             9        5         6       2        2   
2  10002722       3      2             9        4         4       1        1   
3  10002897       4      1            11        7         7       1        1   
4  10004677       1      1             4        1         7       2        2   

   AMDELT  AHLTMDE  ...  SNRLGIMP  SNRLDCSN  SNRLFRND  CIG30USE  IRALCFY  \
0     2.0      NaN  ...         4         3         2        30      993   
1     2.0      NaN  ...         1         2         2        24      350   
2     2.0      NaN  ...         1         1         2        91        4   
3     2.0      NaN  ...         1         1         1        91      156   
4     NaN      NaN  ...        99        99        99        91      993   

   HEALTH  WRKDHRSWK2  IRHHSIZ2  IRKI17_2  target  
0       3          55         1         1       0  
1       2          40         2         1       1  
2       3          41         3         1       0  
3       3          50         2         1       0  
4       3         999         3         2       0  

[5 rows x 33 columns]

## 결측치 확인 

In [24]:
df_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32893 entries, 0 to 32892
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   QUESTID2      32893 non-null  int64  
 1   CATAG6        32893 non-null  int64  
 2   IRSEX         32893 non-null  int64  
 3   IREDUHIGHST2  32893 non-null  int64  
 4   IRPINC3       32893 non-null  int64  
 5   IRFAMIN3      32893 non-null  int64  
 6   PDEN10        32893 non-null  int64  
 7   COUTYP4       32893 non-null  int64  
 8   AMDELT        26079 non-null  float64
 9   AHLTMDE       5302 non-null   float64
 10  AALTMDE       5302 non-null   float64
 11  DSTWORST      32893 non-null  int64  
 12  ADDPREV       32893 non-null  int64  
 13  SMIPP_U       27170 non-null  float64
 14  DSTNRV30      32893 non-null  int64  
 15  DSTHOP30      32893 non-null  int64  
 16  DSTRST30      32893 non-null  int64  
 17  DSTCHR30      32893 non-null  int64  
 18  DSTEFF30      32893 non-nu

## DATA Cleaning !!

In [25]:
# Create a copy df that we will modify for cleaning
df2 = df_20.copy(deep=True)
colums = pd.Series(df_20.columns)
# Look at the unique values in each column, confirming that special codes exist in our data
for i, col in zip(range(len(colums)), colums):
    print(col)
    print(df2[colums[i]].unique())
    print("========================")

QUESTID2
[10000182 10001831 10002722 ... 43074600 43074630 43075406]
CATAG6
[4 3 1 2 5 6]
IRSEX
[1 2]
IREDUHIGHST2
[ 9 11  4 10  6  8  3  2  7  5  1]
IRPINC3
[7 5 4 1 3 2 6]
IRFAMIN3
[7 6 4 5 2 1 3]
PDEN10
[3 2 1]
COUTYP4
[3 2 1]
AMDELT
[ 2. nan  1.]
AHLTMDE
[nan  1.  0.]
AALTMDE
[nan  0.  1.]
DSTWORST
[ 2  1 99 98 94 97 85]
ADDPREV
[ 2  1 99 98 97 94 85]
SMIPP_U
[0.00899813 0.04104224 0.02269539 ... 0.5602212  0.3160603  0.06361628]
DSTNRV30
[ 5  3  2  4 99  1 98 97 94 85]
DSTHOP30
[ 5  3  4 99  2  1 98 97 94 85]
DSTRST30
[ 5  3  4 99  1  2 98 94 97 85]
DSTCHR30
[ 5  4  3 99  2  1 98 94 97 85]
DSTEFF30
[ 5  4 99  2  3  1 98 94 97 85]
DSTNGD30
[ 5  4 99  3  2  1 98 94 97 85]
K6SCMAX
[ 0. 17. 10.  3. nan  5.  4.  6. 21.  7.  9. 13. 24. 18. 11. 12. 23. 20.
  8.  1. 15.  2. 22. 16. 14. 19.]
WHODASC2
[ 0.  9. 10.  2. nan  5. 18.  3.  4.  1. 12. 14. 17.  7.  6. 23.  8. 24.
 11. 13. 19. 16. 20. 15. 21. 22.]
SNRLGSVC
[ 1 99  3  4  2  5  6 94 98 97 85]
SNRLGIMP
[ 4  1 99  3  2 98 94 97 85]
SNR

In [26]:
cont_cols = [
    "CATAG6",
    "IRSEX",
    "IREDUHIGHST2",
    "IRPINC3",
    "IRFAMIN3"
]

cols_99 = ['DSTWORST','ADDPREV','DSTNRV30','DSTHOP30','DSTRST30','DSTCHR30','DSTEFF30','DSTNGD30','SNRLGSVC','SNRLGIMP','SNRLDCSN','SNRLFRND','HEALTH']
cols_999 = ['WRKDHRSWK2','IRALCFY']

# The columns without categorical data are all ordinal
#ord_cols = [x for x in cols if x not in cont_cols]

# Function that cleans continuous numerical data counting by year
def clean_999data(x):

    # Survey codes for "Bad Data", Don't Know, Skip, Refused, or Blank
    if ((x == -9) |
    (x == 985) |
    (x == 989) |
    ((x >= 994) & (x < 1000))):
        return np.nan

    # Codes for "Have never done..." or "Have not done in the past X days"
    # Equivalent to 0 for numbered questions
    if ((x == 991) | 
    (x == 993)):
        return 0

    # Ignore value if conditions don't match
    return x 

# Function that cleans all other special data codes
def clean_99data(x):

    # Survey codes for "Bad Data", Don't Know, Skip, Refused, or Blank
    if ((x == -9) |
    ((x >= 94) & (x < 100)) |
    (x == 84) |
    (x == 85) |
    (x == 89)):
        return np.nan

    # Codes for "Have never done..." or "Have not done in the past X days"
    # Equivalent to 0 for numbered questions
    if ((x == 91) |
    (x == 93)):
        return 0

    # Ignore value if conditions don't match
    return x 

In [27]:
# Look at the unique values in each column, confirming that special codes exist in our data


for i, col in zip(range(len(colums)), colums):
    print(col)
    print(df2[colums[i]].unique())
    print("========================")

QUESTID2
[10000182 10001831 10002722 ... 43074600 43074630 43075406]
CATAG6
[4 3 1 2 5 6]
IRSEX
[1 2]
IREDUHIGHST2
[ 9 11  4 10  6  8  3  2  7  5  1]
IRPINC3
[7 5 4 1 3 2 6]
IRFAMIN3
[7 6 4 5 2 1 3]
PDEN10
[3 2 1]
COUTYP4
[3 2 1]
AMDELT
[ 2. nan  1.]
AHLTMDE
[nan  1.  0.]
AALTMDE
[nan  0.  1.]
DSTWORST
[ 2  1 99 98 94 97 85]
ADDPREV
[ 2  1 99 98 97 94 85]
SMIPP_U
[0.00899813 0.04104224 0.02269539 ... 0.5602212  0.3160603  0.06361628]
DSTNRV30
[ 5  3  2  4 99  1 98 97 94 85]
DSTHOP30
[ 5  3  4 99  2  1 98 97 94 85]
DSTRST30
[ 5  3  4 99  1  2 98 94 97 85]
DSTCHR30
[ 5  4  3 99  2  1 98 94 97 85]
DSTEFF30
[ 5  4 99  2  3  1 98 94 97 85]
DSTNGD30
[ 5  4 99  3  2  1 98 94 97 85]
K6SCMAX
[ 0. 17. 10.  3. nan  5.  4.  6. 21.  7.  9. 13. 24. 18. 11. 12. 23. 20.
  8.  1. 15.  2. 22. 16. 14. 19.]
WHODASC2
[ 0.  9. 10.  2. nan  5. 18.  3.  4.  1. 12. 14. 17.  7.  6. 23.  8. 24.
 11. 13. 19. 16. 20. 15. 21. 22.]
SNRLGSVC
[ 1 99  3  4  2  5  6 94 98 97 85]
SNRLGIMP
[ 4  1 99  3  2 98 94 97 85]
SNR

In [28]:
from pandas.core.dtypes.dtypes import CategoricalDtype

# Apply clean_data functions
df2[cols_99] = df2[cols_99].applymap(clean_99data)
df2[cols_999] = df2[cols_999].applymap(clean_999data)

cals_cate = ['AMDELT','DSTWORST','ADDPREV','ADDPREV','IRSEX']
df2['AMDELT'] =df2['AMDELT']-1
df2['DSTWORST'] =df2['DSTWORST']-1
df2['ADDPREV'] =df2['ADDPREV']-1
df2['IRSEX'] =df2['IRSEX']-1

df2['AMDELT'] =df2['AMDELT'].astype('category')
df2['DSTWORST'] =df2['DSTWORST'].astype('category')
df2['ADDPREV'] =df2['ADDPREV'].astype('category')
df2['IRSEX'] =df2['IRSEX'].astype('category')


df2['AHLTMDE'] =df2['AHLTMDE'].astype('category')
df2['AALTMDE'] =df2['AALTMDE'].astype('category')


df2['target'] =df2['target'].astype('category')



In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32893 entries, 0 to 32892
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   QUESTID2      32893 non-null  int64   
 1   CATAG6        32893 non-null  int64   
 2   IRSEX         32893 non-null  category
 3   IREDUHIGHST2  32893 non-null  int64   
 4   IRPINC3       32893 non-null  int64   
 5   IRFAMIN3      32893 non-null  int64   
 6   PDEN10        32893 non-null  int64   
 7   COUTYP4       32893 non-null  int64   
 8   AMDELT        26079 non-null  category
 9   AHLTMDE       5302 non-null   category
 10  AALTMDE       5302 non-null   category
 11  DSTWORST      26231 non-null  category
 12  ADDPREV       26196 non-null  category
 13  SMIPP_U       27170 non-null  float64 
 14  DSTNRV30      26321 non-null  float64 
 15  DSTHOP30      26309 non-null  float64 
 16  DSTRST30      26290 non-null  float64 
 17  DSTCHR30      26306 non-null  float64 
 18  DSTEFF

In [30]:
# Look at the unique values in each column, confirming that special codes exist in our data
for i, col in zip(range(len(colums)), colums):
    print(col)
    print(df2[colums[i]].unique())
    print("========================")

QUESTID2
[10000182 10001831 10002722 ... 43074600 43074630 43075406]
CATAG6
[4 3 1 2 5 6]
IRSEX
[0, 1]
Categories (2, int64): [0, 1]
IREDUHIGHST2
[ 9 11  4 10  6  8  3  2  7  5  1]
IRPINC3
[7 5 4 1 3 2 6]
IRFAMIN3
[7 6 4 5 2 1 3]
PDEN10
[3 2 1]
COUTYP4
[3 2 1]
AMDELT
[1.0, NaN, 0.0]
Categories (2, float64): [0.0, 1.0]
AHLTMDE
[NaN, 1.0, 0.0]
Categories (2, float64): [0.0, 1.0]
AALTMDE
[NaN, 0.0, 1.0]
Categories (2, float64): [0.0, 1.0]
DSTWORST
[1.0, 0.0, NaN]
Categories (2, float64): [0.0, 1.0]
ADDPREV
[1.0, 0.0, NaN]
Categories (2, float64): [0.0, 1.0]
SMIPP_U
[0.00899813 0.04104224 0.02269539 ... 0.5602212  0.3160603  0.06361628]
DSTNRV30
[ 5.  3.  2.  4. nan  1.]
DSTHOP30
[ 5.  3.  4. nan  2.  1.]
DSTRST30
[ 5.  3.  4. nan  1.  2.]
DSTCHR30
[ 5.  4.  3. nan  2.  1.]
DSTEFF30
[ 5.  4. nan  2.  3.  1.]
DSTNGD30
[ 5.  4. nan  3.  2.  1.]
K6SCMAX
[ 0. 17. 10.  3. nan  5.  4.  6. 21.  7.  9. 13. 24. 18. 11. 12. 23. 20.
  8.  1. 15.  2. 22. 16. 14. 19.]
WHODASC2
[ 0.  9. 10.  2. nan  5. 

/usr/local/lib/python3.7/dist-packages/pandas/io/formats/format.py:1429: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  for val, m in zip(values.ravel(), mask.ravel())


In [31]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32893 entries, 0 to 32892
Data columns (total 33 columns):
 #   Column        Non-Null Count  Dtype   
---  ------        --------------  -----   
 0   QUESTID2      32893 non-null  int64   
 1   CATAG6        32893 non-null  int64   
 2   IRSEX         32893 non-null  category
 3   IREDUHIGHST2  32893 non-null  int64   
 4   IRPINC3       32893 non-null  int64   
 5   IRFAMIN3      32893 non-null  int64   
 6   PDEN10        32893 non-null  int64   
 7   COUTYP4       32893 non-null  int64   
 8   AMDELT        26079 non-null  category
 9   AHLTMDE       5302 non-null   category
 10  AALTMDE       5302 non-null   category
 11  DSTWORST      26231 non-null  category
 12  ADDPREV       26196 non-null  category
 13  SMIPP_U       27170 non-null  float64 
 14  DSTNRV30      26321 non-null  float64 
 15  DSTHOP30      26309 non-null  float64 
 16  DSTRST30      26290 non-null  float64 
 17  DSTCHR30      26306 non-null  float64 
 18  DSTEFF

# 분석 고?

In [32]:
import numpy as np
#import pandas as pd

from sklearn.pipeline import make_pipeline
from sklearn.pipeline import Pipeline


#from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier
from sklearn.ensemble import AdaBoostClassifier
#from sklearn import svm

from category_encoders import OrdinalEncoder
from category_encoders import TargetEncoder
from category_encoders import BinaryEncoder
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder


from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score


/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [33]:
from scipy.stats import randint, uniform
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV


In [34]:
from sklearn.model_selection import train_test_split
target = 'target'

# 80/20 비율로 학습/테스트 데이터를 분리합니다.
Train, test = train_test_split(df2, train_size=0.80, test_size=0.20, 
                              stratify=df2[target], random_state=2)


train, val = train_test_split(Train, train_size=0.80, test_size=0.20, 
                              stratify=Train[target], random_state=2)


In [35]:
#target = 'memory capacity'
target = 'target'

features = train.columns.drop([target, 'QUESTID2'])
X_train = train[features]
y_train = train[target]

X_val = val[features]
y_val = val[target]

X_test = test[features]
y_test = test[target]

In [36]:
# 클래스의 비율
y_train.value_counts(normalize=True)

0    0.837585
1    0.162415
Name: target, dtype: float64

In [37]:
ratio = 0.16/0.84
ratio

0.1904761904761905

In [38]:

#  variables settings for encodings
cate_cols =['IRSEX','DSTWORST','ADDPREV']     # for encoding categry data
conti_cols = ['SMIPP_U']                      # for imputing continuous data 
ordinal_cols = [i for i in features.tolist() if i not in cate_cols+conti_cols ]  # for encoding ordinal data


In [39]:
# Create a preprocessor from ColumnTransformer.
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer(transformers=[
    ('impute', SimpleImputer(),[i for i, x in enumerate(features.tolist()) if x in conti_cols] ),                                         
    ('cate',BinaryEncoder(), [i for i, x in enumerate(features.tolist()) if x in cate_cols]),
    ('Ord', OrdinalEncoder(), [i for i, x in enumerate(features.tolist()) if x in ordinal_cols])])

In [40]:
# Parameter grid for RandomizedSearchCV
model_grid = {
    'random_forest': {
        'model':RandomForestClassifier(random_state=15, n_jobs=50, n_estimators=500),
        'params': {
            'estimator__n_estimators': randint(50, 1000),
            'estimator__max_depth': [5,6,7,8,9,10],
            'estimator__criterion':['gini', 'entropy'],
            'estimator__class_weight':['balanced', 'balanced_subsample']
        }
    },

    'xgb_classifier': {
        'model': XGBClassifier(n_estimators=1000, early_stopping_rounds  = 100,subsample=0.8, 
                               colsample_bytree=0.8, verbosity=2, n_jobs=500, scale_pos_weight=ratio, learning_rate=0.15),
        'params': {
            'estimator__n_estimators': randint(50, 1000),
            'estimator__max_depth': [5,6,7,8],
            'estimator__min_child_weight': [2,3]
        }
    },
    'adb_classifier': {
        'model': AdaBoostClassifier(n_estimators=1000, learning_rate=0.2, random_state = 15),
        'params': {
            'estimator__n_estimators': randint(50, 1000)
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(random_state=15, n_jobs=300),
        'params': {
            'estimator__C': [0.085, 0.09, 0.092],
            'estimator__solver':['lbfgs', 'liblinear'],
        }
    }
}

In [41]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import FunctionTransformer

In [42]:
model_grid

{'adb_classifier': {'model': AdaBoostClassifier(learning_rate=0.2, n_estimators=1000, random_state=15),
  'params': {'estimator__n_estimators': <scipy.stats._distn_infrastructure.rv_frozen at 0x7f2e3c1e3d50>}},
 'logistic_regression': {'model': LogisticRegression(n_jobs=300, random_state=15),
  'params': {'estimator__C': [0.085, 0.09, 0.092],
   'estimator__solver': ['lbfgs', 'liblinear']}},
 'random_forest': {'model': RandomForestClassifier(n_estimators=500, n_jobs=50, random_state=15),
  'params': {'estimator__class_weight': ['balanced', 'balanced_subsample'],
   'estimator__criterion': ['gini', 'entropy'],
   'estimator__max_depth': [5, 6, 7, 8, 9, 10],
   'estimator__n_estimators': <scipy.stats._distn_infrastructure.rv_frozen at 0x7f2e3c1e39d0>}},
 'xgb_classifier': {'model': XGBClassifier(colsample_bytree=0.8, early_stopping_rounds=100,
                learning_rate=0.15, n_estimators=1000, n_jobs=500,
                scale_pos_weight=0.1904761904761905, subsample=0.8, verbosity=2

In [43]:
# 'xgb_classifier'
#  'random_forest'
#  'logistic_regression'
#  'adb_classifier'

model={}
scores = []
models=[]   

model_name='random_forest'
# Create our pipeline
pipe = Pipeline(steps=[
      ('impute', SimpleImputer()),
      ('round', FunctionTransformer(np.round)),
      ('preprocessor', preprocessor),
      ('estimator', model_grid[model_name]['model'])
  ])

model[model_name] = RandomizedSearchCV(estimator=pipe, param_distributions= model_grid[model_name]['params'],n_jobs=50, cv=5, return_train_score=True, n_iter=100, random_state=42,verbose=10,scoring = 'f1_weighted' ,refit=True)
model[model_name].fit(X_train, y_train)
scores.append({
    'model': model_name,
    'best_score:': model[model_name].best_score_,
    'best_params': model[model_name].best_params_ })

models.append({'model_best_esti': model[model_name].best_estimator_})

Fitting 5 folds for each of 100 candidates, totalling 500 fits


In [44]:
model[model_name].best_estimator_

Pipeline(steps=[('impute', SimpleImputer()),
                ('round',
                 FunctionTransformer(func=<function round_ at 0x7f2e29579710>)),
                ('preprocessor',
                 ColumnTransformer(transformers=[('impute', SimpleImputer(),
                                                  [12]),
                                                 ('cate', BinaryEncoder(),
                                                  [1, 10, 11]),
                                                 ('Ord', OrdinalEncoder(),
                                                  [0, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   13, 14, 15, 16, 17, 18, 19,
                                                   20, 21, 22, 23, 24, 25, 26,
                                                   27, 28, 29, 30])])),
                ('estimator',
                 RandomForestClassifier(class_weight='balanced_subsample',
                                        max_depth=10, 

In [45]:
x_predict = model[model_name].best_estimator_.predict(X_val)



In [46]:
from sklearn.metrics import classification_report, accuracy_score,roc_auc_score



print("Classification roc_auc_score: %f\n" %(roc_auc_score(y_val, x_predict) ))
print("Classification Score: %f\n" %(accuracy_score(y_val, x_predict) ))
print("Classification:\n", classification_report(y_val, x_predict))



Classification roc_auc_score: 0.779255

Classification Score: 0.813414

Classification:
               precision    recall  f1-score   support

           0       0.94      0.83      0.88      4408
           1       0.45      0.73      0.56       855

    accuracy                           0.81      5263
   macro avg       0.70      0.78      0.72      5263
weighted avg       0.86      0.81      0.83      5263



In [51]:
x_predict = model[model_name].best_estimator_.predict(X_test)



In [52]:
from sklearn.metrics import classification_report, accuracy_score,roc_auc_score



print("Classification roc_auc_score: %f\n" %(roc_auc_score(y_test, x_predict) ))
print("Classification Score: %f\n" %(accuracy_score(y_test, x_predict) ))
print("Classification:\n", classification_report(y_test, x_predict))



Classification roc_auc_score: 0.780937

Classification Score: 0.817449

Classification:
               precision    recall  f1-score   support

           0       0.94      0.84      0.88      5510
           1       0.46      0.73      0.56      1069

    accuracy                           0.82      6579
   macro avg       0.70      0.78      0.72      6579
weighted avg       0.86      0.82      0.83      6579



In [49]:
scores

[{'best_params': {'estimator__class_weight': 'balanced_subsample',
   'estimator__criterion': 'gini',
   'estimator__max_depth': 10,
   'estimator__n_estimators': 799},
  'best_score:': 0.8328944451610832,
  'model': 'random_forest'}]

In [50]:
 model.fit(X_train,y_train)

AttributeError: ignored

In [ ]:
xgb_best = model['xgb_classifier'].best_estimator_
xgb_best

## Choosing a Model??


In [ ]:
y_test[y_test==1].size

In [ ]:


print("Dummy Model Score: ", y_test[y_test==1].size/y_test.shape[0])


In [ ]:
xgb_predict = xgb_best.predict(X_val)



In [ ]:
from sklearn.metrics import classification_report, accuracy_score


print("XGB Classification Score: %f\n" %(accuracy_score(y_val, xgb_predict) ))
print("XGB Classification:\n", classification_report(y_val, xgb_predict))



## Feature importances

In [ ]:
rf_encoder = OrdinalEncoder()

X_train_encoded =rf_encoder.fit_transform(X_train)
X_val_encoded =rf_encoder.transform(X_val)


In [ ]:
X_val_encoded.shape

In [ ]:
X_train.isnull().sum()

In [ ]:
y_train.shape

In [ ]:
rf.feature_importances_.shape

In [ ]:
# 특성 중요도
#rf_encoder = model.best_estimator_.named_steps['preprocessor']
#_train_encoded =rf_encoder.transform(X_train)

rf = xgb_best.named_steps['estimator']
#rf.fit(X_train,y_train)
importances = pd.Series(rf.feature_importances_, X_train.columns)

%matplotlib inline
import matplotlib.pyplot as plt

n = 20
plt.figure(figsize=(10,n/2))
plt.title(f'Top {n} features')
importances.sort_values()[-n:].plot.barh();

In [ ]:
import eli5
from eli5.sklearn import PermutationImportance

# permuter 생성
permuter = PermutationImportance(
    xgb_best,
    scoring= 'roc_auc', #'neg_mean_absolute_error',
    n_iter=5,
    random_state=42)

# permutation importance 계산
permuter.fit(X_val, y_val)

# 결과 확인
feature_names = list(X_val.columns)
pd.Series(permuter.feature_importances_, feature_names).sort_values(ascending=False)

In [ ]:
xgb_best.named_steps

In [ ]:
# 특성별 score 확인
eli5.show_weights(
    permuter, 
    top=None, # top n 지정 가능, None 일 경우 모든 특성 
    feature_names=feature_names # list 형식으로 넣어야 합니다
)

## PDP

In [ ]:
from pdpbox.pdp import pdp_isolate, pdp_plot,pdp_interact,pdp_interact_plot
# dpi(dots per inch) 수치를 조정해 이미지 화질을 조정 할 수 있습니다
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 144

In [ ]:
X_val.columns

In [ ]:
from category_encoders import OrdinalEncoder
from sklearn.metrics import r2_score
from xgboost import XGBRegressor

encoder = preprocessor
X_train_encoded = encoder.fit_transform(X_train) # 학습데이터
X_val_encoded = encoder.transform(X_val) # 검증데이터



model = XGBClassifier(
    n_estimators=1000,  # <= 1000 트리로 설정했지만, early stopping 에 따라 조절됩니다.
    max_depth=7,        # default=3, high cardinality 특성을 위해 기본보다 높여 보았습니다.
    learning_rate=0.2,
#     scale_pos_weight=ratio, # imbalance 데이터 일 경우 비율을 적용합니다.
    n_jobs=-1
)

eval_set = [(X_train_encoded, y_train), 
            (X_val_encoded, y_val)]

model.fit(X_train_encoded, y_train, 
          eval_set=eval_set,
          eval_metric='error', # #(wrong cases)/#(all cases)
          early_stopping_rounds=50
         ) # 50 rounds 동안 스코어의 개선이 없으면 멈춤

In [ ]:
model.evals_result()

In [ ]:
# monotonic constraints 효과, 단조증가해야 하는 특성이 오류로 비단조 증가할때 변수마다 적용 가능합니다.
from IPython.display import HTML, display
display(HTML('<table><tr><td><img src="https://xiaoxiaowang87.github.io/images/2016-11-20-monotonicity_constraint/no_constraint_one_feature.png" width="300" /></td><td><img src="https://xiaoxiaowang87.github.io/images/2016-11-20-monotonicity_constraint/w_constraint_one_feature.png" width="300" /></td></tr></table>'))

In [ ]:
%matplotlib inline

results = model.evals_result()
train_error = results['validation_0']['error']
val_error = results['validation_1']['error']

epoch = range(1, len(train_error)+1)
plt.figure()
plt.plot(epoch, train_error, label='Train')
plt.plot(epoch, val_error, label='Validation')
plt.ylabel('Classification Error')
plt.xlabel('Model Complexity (n_estimators)')
#plt.ylim((0.15, 0.25)) # Zoom in
plt.legend();
plt.show()

In [ ]:
isolated = pdp_isolate(
    model=boosting, 
    dataset=X_val_encoded, 
    model_features=X_val_encoded.columns, 
    feature=feature
)

In [ ]:
X_val_encoded

In [ ]:
feature = 'CIG30USE'
isolated = pdp_isolate(
    model=rf_best, 
    dataset=X_train, 
    model_features=X_val.columns, 
    feature=feature
)

In [ ]:
pdp_plot(isolated, feature_name=feature);


In [ ]:
# 2D PDP
features = ['sex', 'age']

interaction = pdp_interact(
    model=rf, 
    dataset=X_val, 
    model_features=X_val.columns, 
    features=features
)

pdp_interact_plot(interaction, plot_type='grid', feature_names=features);